categories:
- service
- 服務
conversations:
- - 早安
  - 您好,歡迎光臨!! 請問有需要什麼樣的服務
- - 午安
  - 您好歡迎光臨!! 請問有需要什麼樣的服務
- - 晚安
  - 您好歡迎光臨!! 請問有需要什麼樣的服務
- - 我要買菸
  - 請問需要什麼樣的菸
- - 我想買菸
  - 請問需要什麼樣的菸
- - 我想要買菸
  - 請問需要什麼樣的菸
- - 七星 
  - 口味有淡的和深的請問要選哪一種
- - 我要買酒
  - 請問需要什麼樣的酒
- - 我想買酒
  - 請問需要什麼樣的酒
- - 我想要買酒
  - 請問需要什麼樣的酒
- - 我要訂購商品
  - 請問需要訂購什麼樣的商品
- - 我想訂購商品
  - 請問需要訂購什麼樣的商品
- - 我想要訂購商品
  - 請問需要訂購什麼樣的商品
- - 我要找生活用品
  - 請問要找哪類生活用品
- - 我想找生活用品
  - 請問要找哪類生活用品
- - 我想要找生活用品
  - 請問要找哪類生活用品
- - 我要買冰淇淋
  - 請問需要買哪種品牌的冰淇淋
- - 我想買冰淇淋
  - 請問需要買哪種品牌的冰淇淋
- - 我想要買冰淇淋
  - 請問需要買哪種品牌的冰淇淋
- - 我要買零食
  - 請問需要哪一種類的零食
- - 我想買零食
  - 請問需要哪一種類的零食
- - 我想要買零食
  - 請問需要哪一種類的零食

# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   - 
# - - 
#   -